version: '3.8'

services:
  roboflow-inference:
    image: roboflow/roboflow-inference-server-cpu
    container_name: roboflow-inference-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:9001:9001"
    environment:
      - ALLOW_ORIGINS=${DOMAIN_URL:-*}
      - CORS_ALLOW_ORIGINS=${DOMAIN_URL:-*}
    deploy:
      resources:
        limits:
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: plate-pay-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      roboflow-inference:
        condition: service_healthy